import { useState, useEffect } from 'react';

export interface ServiceCaseStudy {
  id: string;
  service_type: string;
  title: string;
  description: string;
  client_name: string;
  industry: string;
  results: { [key: string]: string };
  image_url?: string;
  is_active: boolean;
  is_featured: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface ServiceStat {
  id: string;
  service_type: string;
  stat_label: string;
  stat_value: string;
  stat_description?: string;
  icon_name?: string;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export interface ServiceReview {
  id: string;
  service_type: string;
  client_name: string;
  company: string;
  rating: number;
  review_text: string;
  results_achieved?: string;
  is_active: boolean;
  is_featured: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export const useServiceData = (serviceType: string) => {
  const [caseStudies, setCaseStudies] = useState<ServiceCaseStudy[]>([]);
  const [stats, setStats] = useState<ServiceStat[]>([]);
  const [reviews, setReviews] = useState<ServiceReview[]>([]);

  useEffect(() => {
    const generateServiceData = () => {
      // Enhanced case studies - 8 per service
      const caseStudiesData: { [key: string]: ServiceCaseStudy[] } = {
        'amazon-advertising': [
          {
            id: '1',
            service_type: 'amazon-advertising',
            title: 'Increased Kitchen Appliance Sales by 450%',
            description: 'A kitchen appliance brand struggling with low visibility transformed their Amazon presence through strategic PPC campaigns and listing optimization.',
            client_name: 'KitchenPro',
            industry: 'Home & Kitchen',
            results: { 'sales_increase': '+450%', 'acos_reduction': '-35%', 'roas': '6.2x' },
            image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '2',
            service_type: 'amazon-advertising',
            title: 'Electronics Brand Achieves 8x ROAS',
            description: 'Premium electronics brand optimized their sponsored products and brand campaigns to dominate competitive keywords.',
            client_name: 'TechElite',
            industry: 'Electronics',
            results: { 'roas': '8.1x', 'click_through_rate': '+65%', 'conversion_rate': '+42%' },
            image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '3',
            service_type: 'amazon-advertising',
            title: 'Beauty Brand Scales to 7-Figure Revenue',
            description: 'Emerging beauty brand leveraged Amazon DSP and sponsored display ads to build brand awareness and drive consistent growth.',
            client_name: 'GlowBeauty',
            industry: 'Beauty & Personal Care',
            results: { 'revenue_growth': '+890%', 'brand_searches': '+320%', 'market_share': '+15%' },
            image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '4',
            service_type: 'amazon-advertising',
            title: 'Sports Equipment Brand Dominates Category',
            description: 'Fitness equipment manufacturer used strategic keyword targeting and competitor analysis to capture market leadership.',
            client_name: 'FitGear Pro',
            industry: 'Sports & Outdoors',
            results: { 'market_position': '#1 Ranking', 'organic_traffic': '+280%', 'sales_velocity': '+190%' },
            image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '5',
            service_type: 'amazon-advertising',
            title: 'Home Decor Brand Reduces ACoS by 60%',
            description: 'Interior design products company optimized their campaign structure and bid management for maximum profitability.',
            client_name: 'HomeStyle',
            industry: 'Home & Garden',
            results: { 'acos_reduction': '-60%', 'profit_margin': '+45%', 'impressions': '+150%' },
            image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '6',
            service_type: 'amazon-advertising',
            title: 'Pet Supplies Brand Achieves Market Leadership',
            description: 'Premium pet food brand utilized video ads and brand store optimization to build customer loyalty and repeat purchases.',
            client_name: 'PetLux',
            industry: 'Pet Supplies',
            results: { 'repeat_purchases': '+75%', 'brand_loyalty': '+85%', 'video_views': '2.5M+' },
            image_url: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '7',
            service_type: 'amazon-advertising',
            title: 'Fashion Brand Increases Visibility by 400%',
            description: 'Apparel brand transformed their Amazon presence through strategic sponsored brand campaigns and influencer partnerships.',
            client_name: 'StyleForward',
            industry: 'Fashion',
            results: { 'brand_visibility': '+400%', 'social_engagement': '+250%', 'new_customers': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '8',
            service_type: 'amazon-advertising',
            title: 'Tools Brand Captures 40% Market Share',
            description: 'Professional tools manufacturer leveraged B2B targeting and bulk purchase optimization to dominate their category.',
            client_name: 'ProTools',
            industry: 'Tools & Hardware',
            results: { 'market_share': '40%', 'b2b_sales': '+320%', 'bulk_orders': '+150%' },
            image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'google-advertising': [
          {
            id: '9',
            service_type: 'google-advertising',
            title: 'SaaS Company Achieves 12x ROAS with Google Ads',
            description: 'B2B software company optimized their Google Ads campaigns to target high-intent keywords and improve conversion rates.',
            client_name: 'CloudTech Solutions',
            industry: 'Software',
            results: { 'roas': '12.3x', 'cost_per_lead': '-70%', 'conversion_rate': '+85%' },
            image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '10',
            service_type: 'google-advertising',
            title: 'E-commerce Store Scales to $2M Annual Revenue',
            description: 'Online retailer leveraged Google Shopping and Performance Max campaigns to dramatically increase sales and market reach.',
            client_name: 'ShopSmart',
            industry: 'Retail',
            results: { 'annual_revenue': '$2M+', 'shopping_traffic': '+350%', 'product_visibility': '+280%' },
            image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '11',
            service_type: 'google-advertising',
            title: 'Local Service Business Dominates Market',
            description: 'HVAC company used Google Local Services and targeted search campaigns to become the top choice in their region.',
            client_name: 'CoolAir Pro',
            industry: 'Home Services',
            results: { 'local_dominance': '#1 Position', 'service_calls': '+220%', 'customer_base': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1581578017426-462ea8f578dc?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '12',
            service_type: 'google-advertising',
            title: 'Healthcare Practice Increases Patient Volume by 300%',
            description: 'Dental practice optimized their Google Ads to target local patients and improve appointment booking rates.',
            client_name: 'Smile Dental',
            industry: 'Healthcare',
            results: { 'patient_volume': '+300%', 'appointment_rate': '+150%', 'local_reach': '+250%' },
            image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '13',
            service_type: 'google-advertising',
            title: 'Education Platform Grows User Base by 500%',
            description: 'Online learning platform used YouTube ads and search campaigns to reach students and educators worldwide.',
            client_name: 'LearnFast',
            industry: 'Education',
            results: { 'user_growth': '+500%', 'course_enrollments': '+420%', 'video_engagement': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '14',
            service_type: 'google-advertising',
            title: 'Real Estate Agency Generates 150+ Qualified Leads Monthly',
            description: 'Property management company leveraged Google Ads to target homebuyers and sellers in their target markets.',
            client_name: 'Prime Properties',
            industry: 'Real Estate',
            results: { 'monthly_leads': '150+', 'qualified_prospects': '+280%', 'property_sales': '+90%' },
            image_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '15',
            service_type: 'google-advertising',
            title: 'Financial Services Firm Reduces CAC by 65%',
            description: 'Investment advisory firm optimized their Google Ads targeting and landing pages to attract high-value clients.',
            client_name: 'WealthGuard',
            industry: 'Financial Services',
            results: { 'cac_reduction': '-65%', 'client_value': '+340%', 'consultation_rate': '+120%' },
            image_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '16',
            service_type: 'google-advertising',
            title: 'Restaurant Chain Increases Foot Traffic by 200%',
            description: 'Multi-location restaurant used Google Ads location extensions and local campaigns to drive customers to stores.',
            client_name: 'TasteBud Bistro',
            industry: 'Food & Beverage',
            results: { 'foot_traffic': '+200%', 'online_orders': '+150%', 'brand_awareness': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'meta-advertising': [
          {
            id: '17',
            service_type: 'meta-advertising',
            title: 'Fashion Brand Achieves 15x ROAS on Meta',
            description: 'Luxury fashion brand leveraged Instagram and Facebook ads to reach target demographics and drive premium sales.',
            client_name: 'LuxeStyle',
            industry: 'Fashion',
            results: { 'roas': '15.2x', 'brand_engagement': '+450%', 'premium_sales': '+320%' },
            image_url: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '18',
            service_type: 'meta-advertising',
            title: 'Fitness App Grows to 500K Active Users',
            description: 'Health and fitness mobile app used Meta\'s app install campaigns and video content to build a massive user base.',
            client_name: 'FitLife App',
            industry: 'Health & Fitness',
            results: { 'active_users': '500K+', 'app_installs': '+800%', 'user_retention': '+85%' },
            image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '19',
            service_type: 'meta-advertising',
            title: 'Home Decor Brand Builds Community of 100K Followers',
            description: 'Interior design brand created engaging content and targeted campaigns to build a loyal social media community.',
            client_name: 'CozyHome',
            industry: 'Home & Garden',
            results: { 'community_size': '100K+', 'engagement_rate': '+280%', 'ugc_content': '5000+' },
            image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '20',
            service_type: 'meta-advertising',
            title: 'Beauty Brand Launches Viral Campaign',
            description: 'Cosmetics startup created viral content and influencer partnerships to achieve massive brand awareness.',
            client_name: 'RadiantGlow',
            industry: 'Beauty',
            results: { 'viral_reach': '10M+', 'influencer_partnerships': '500+', 'brand_mentions': '+650%' },
            image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '21',
            service_type: 'meta-advertising',
            title: 'Local Restaurant Increases Reservations by 300%',
            description: 'Fine dining restaurant used location-based targeting and food photography to attract local customers.',
            client_name: 'Gourmet Corner',
            industry: 'Food & Beverage',
            results: { 'reservations': '+300%', 'local_awareness': '+250%', 'repeat_customers': '+120%' },
            image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '22',
            service_type: 'meta-advertising',
            title: 'E-learning Platform Reaches 1M Students',
            description: 'Online education platform used video ads and testimonials to attract students and educators worldwide.',
            client_name: 'EduPro',
            industry: 'Education',
            results: { 'student_base': '1M+', 'course_completion': '+90%', 'global_reach': '50+ countries' },
            image_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '23',
            service_type: 'meta-advertising',
            title: 'Tech Startup Raises $5M in Series A',
            description: 'B2B SaaS startup used targeted campaigns to build brand credibility and attract investors and customers.',
            client_name: 'InnovateTech',
            industry: 'Technology',
            results: { 'funding_raised': '$5M', 'lead_quality': '+400%', 'investor_interest': '+300%' },
            image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '24',
            service_type: 'meta-advertising',
            title: 'Pet Care Brand Builds Loyal Customer Base',
            description: 'Premium pet care products company used emotional storytelling and pet owner targeting to drive sales.',
            client_name: 'PawPerfect',
            industry: 'Pet Care',
            results: { 'customer_loyalty': '+200%', 'subscription_rate': '+150%', 'social_shares': '+350%' },
            image_url: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'walmart-advertising': [
          {
            id: '25',
            service_type: 'walmart-advertising',
            title: 'Consumer Electronics Brand Dominates Walmart',
            description: 'Tech accessories brand leveraged Walmart Connect to achieve top rankings and massive sales growth.',
            client_name: 'TechMax',
            industry: 'Electronics',
            results: { 'sales_growth': '+680%', 'category_ranking': '#1', 'walmart_share': '35%' },
            image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '26',
            service_type: 'walmart-advertising',
            title: 'Home Goods Brand Achieves 900% Revenue Growth',
            description: 'Kitchen appliance manufacturer optimized their Walmart presence to capture market-leading position.',
            client_name: 'HomeMaster',
            industry: 'Home & Kitchen',
            results: { 'revenue_growth': '+900%', 'product_visibility': '+450%', 'market_position': 'Leader' },
            image_url: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '27',
            service_type: 'walmart-advertising',
            title: 'Beauty Brand Launches Successfully on Walmart',
            description: 'Skincare brand used strategic advertising and competitive pricing to establish strong Walmart presence.',
            client_name: 'PureGlow',
            industry: 'Beauty & Personal Care',
            results: { 'launch_success': 'Top 10', 'brand_awareness': '+320%', 'customer_reviews': '4.8/5' },
            image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '28',
            service_type: 'walmart-advertising',
            title: 'Sports Brand Captures 40% Category Share',
            description: 'Athletic equipment brand dominated Walmart sports category through strategic advertising and inventory management.',
            client_name: 'ActiveGear',
            industry: 'Sports & Outdoors',
            results: { 'category_share': '40%', 'inventory_turnover': '+250%', 'seasonal_sales': '+400%' },
            image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '29',
            service_type: 'walmart-advertising',
            title: 'Grocery Brand Expands Nationwide',
            description: 'Regional food brand used Walmart advertising to expand from local to national distribution.',
            client_name: 'FarmFresh',
            industry: 'Food & Beverage',
            results: { 'geographic_expansion': 'Nationwide', 'distribution_growth': '+500%', 'brand_recognition': '+280%' },
            image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '30',
            service_type: 'walmart-advertising',
            title: 'Automotive Parts Brand Drives B2B Success',
            description: 'Auto parts manufacturer leveraged Walmart Business to capture commercial and individual customers.',
            client_name: 'AutoPro',
            industry: 'Automotive',
            results: { 'b2b_growth': '+350%', 'commercial_clients': '1000+', 'bulk_orders': '+200%' },
            image_url: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '31',
            service_type: 'walmart-advertising',
            title: 'Baby Products Brand Becomes Category Leader',
            description: 'Infant care products company used targeted advertising to become the top choice for parents on Walmart.',
            client_name: 'BabyBest',
            industry: 'Baby & Toddler',
            results: { 'category_leadership': '#1 Brand', 'parent_trust': '95%', 'repeat_purchases': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '32',
            service_type: 'walmart-advertising',
            title: 'Health Supplements Brand Achieves Compliance Success',
            description: 'Nutritional supplements company navigated Walmart\'s strict requirements to build a thriving health products business.',
            client_name: 'VitalHealth',
            industry: 'Health & Wellness',
            results: { 'compliance_rate': '100%', 'health_category_growth': '+420%', 'customer_satisfaction': '4.9/5' },
            image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'shopify-development': [
          {
            id: '33',
            service_type: 'shopify-development',
            title: 'Fashion Retailer Increases Conversion Rate by 180%',
            description: 'Clothing brand redesigned their Shopify store with optimized UX and mobile-first design to boost sales.',
            client_name: 'TrendSetters',
            industry: 'Fashion',
            results: { 'conversion_rate': '+180%', 'mobile_sales': '+250%', 'page_speed': '+90%' },
            image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '34',
            service_type: 'shopify-development',
            title: 'Electronics Store Scales to $10M Revenue',
            description: 'Tech retailer built a high-performance Shopify Plus store with advanced inventory management and automation.',
            client_name: 'GadgetHub',
            industry: 'Electronics',
            results: { 'annual_revenue': '$10M+', 'order_processing': '+300%', 'inventory_efficiency': '+150%' },
            image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '35',
            service_type: 'shopify-development',
            title: 'Beauty Brand Launches Multi-Language Store',
            description: 'Cosmetics company expanded globally with a multi-currency, multi-language Shopify store.',
            client_name: 'GlobalGlow',
            industry: 'Beauty',
            results: { 'global_markets': '25+ countries', 'international_sales': '+400%', 'language_support': '12 languages' },
            image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '36',
            service_type: 'shopify-development',
            title: 'Food Brand Creates Subscription Commerce Success',
            description: 'Gourmet food company implemented subscription functionality and automated recurring revenue streams.',
            client_name: 'TasteCraft',
            industry: 'Food & Beverage',
            results: { 'subscription_revenue': '70%', 'customer_retention': '+220%', 'recurring_orders': '15K+' },
            image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '37',
            service_type: 'shopify-development',
            title: 'Home Decor Brand Optimizes for Voice Commerce',
            description: 'Interior design retailer integrated voice shopping capabilities and AI-powered product recommendations.',
            client_name: 'ModernSpaces',
            industry: 'Home & Garden',
            results: { 'voice_orders': '+150%', 'ai_recommendations': '+85%', 'customer_satisfaction': '96%' },
            image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '38',
            service_type: 'shopify-development',
            title: 'Sports Brand Builds Community-Driven Store',
            description: 'Athletic wear brand created an interactive Shopify store with community features and user-generated content.',
            client_name: 'AthleteConnect',
            industry: 'Sports',
            results: { 'community_engagement': '+300%', 'ugc_content': '10K+ posts', 'brand_loyalty': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '39',
            service_type: 'shopify-development',
            title: 'Luxury Brand Creates Premium Shopping Experience',
            description: 'High-end jewelry brand developed an exclusive Shopify experience with virtual try-on and concierge service.',
            client_name: 'LuxeJewels',
            industry: 'Luxury Goods',
            results: { 'average_order_value': '+250%', 'virtual_tryons': '50K+', 'concierge_satisfaction': '98%' },
            image_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '40',
            service_type: 'shopify-development',
            title: 'B2B Manufacturer Streamlines Wholesale Operations',
            description: 'Industrial supplies manufacturer built a B2B-focused Shopify Plus store with custom pricing and bulk ordering.',
            client_name: 'IndustryPro',
            industry: 'Manufacturing',
            results: { 'b2b_efficiency': '+200%', 'bulk_order_processing': '+150%', 'wholesale_growth': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'shopify-integration': [
          {
            id: '41',
            service_type: 'shopify-integration',
            title: 'Omnichannel Retailer Unifies All Sales Channels',
            description: 'Multi-channel retailer integrated Shopify with POS, inventory, and CRM systems for seamless operations.',
            client_name: 'OmniStore',
            industry: 'Retail',
            results: { 'channel_sync': '100%', 'inventory_accuracy': '+95%', 'operational_efficiency': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '42',
            service_type: 'shopify-integration',
            title: 'Subscription Brand Automates Customer Lifecycle',
            description: 'Subscription box company integrated advanced automation tools to optimize customer journey and retention.',
            client_name: 'BoxDelight',
            industry: 'Subscription Commerce',
            results: { 'automation_rate': '85%', 'customer_lifetime_value': '+200%', 'churn_reduction': '-60%' },
            image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '43',
            service_type: 'shopify-integration',
            title: 'Fashion Brand Connects Global Supply Chain',
            description: 'International fashion retailer integrated Shopify with global suppliers and logistics partners.',
            client_name: 'GlobalFashion',
            industry: 'Fashion',
            results: { 'supply_chain_efficiency': '+150%', 'shipping_speed': '+80%', 'global_reach': '40+ countries' },
            image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '44',
            service_type: 'shopify-integration',
            title: 'Electronics Brand Streamlines Returns Process',
            description: 'Tech retailer integrated advanced returns management system to improve customer satisfaction.',
            client_name: 'TechReturn',
            industry: 'Electronics',
            results: { 'return_processing': '+300%', 'customer_satisfaction': '+120%', 'cost_reduction': '-40%' },
            image_url: 'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '45',
            service_type: 'shopify-integration',
            title: 'Health Brand Integrates Compliance Tracking',
            description: 'Supplement company built regulatory compliance tracking into their Shopify operations.',
            client_name: 'HealthTrack',
            industry: 'Health & Wellness',
            results: { 'compliance_rate': '100%', 'audit_efficiency': '+250%', 'regulatory_confidence': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '46',
            service_type: 'shopify-integration',
            title: 'Home Goods Brand Optimizes Fulfillment Network',
            description: 'Furniture retailer integrated with multiple fulfillment centers for faster delivery and lower costs.',
            client_name: 'HomeFast',
            industry: 'Home & Garden',
            results: { 'delivery_speed': '+200%', 'shipping_costs': '-35%', 'fulfillment_accuracy': '+95%' },
            image_url: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '47',
            service_type: 'shopify-integration',
            title: 'Beauty Brand Creates Personalized Experience Engine',
            description: 'Skincare company integrated AI-powered personalization tools for customized product recommendations.',
            client_name: 'PersonalGlow',
            industry: 'Beauty',
            results: { 'personalization_accuracy': '92%', 'conversion_lift': '+160%', 'customer_engagement': '+220%' },
            image_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '48',
            service_type: 'shopify-integration',
            title: 'Food Brand Integrates Cold Chain Management',
            description: 'Frozen food company built temperature monitoring and cold chain logistics into their Shopify operations.',
            client_name: 'FreshFreeze',
            industry: 'Food & Beverage',
            results: { 'temperature_monitoring': '100%', 'product_quality': '+98%', 'waste_reduction': '-70%' },
            image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'website-development': [
          {
            id: '49',
            service_type: 'website-development',
            title: 'Corporate Website Increases Lead Generation by 500%',
            description: 'B2B consulting firm redesigned their website with optimized lead generation funnels and conversion optimization.',
            client_name: 'ConsultPro',
            industry: 'Professional Services',
            results: { 'lead_generation': '+500%', 'conversion_rate': '+180%', 'consultation_bookings': '+320%' },
            image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '50',
            service_type: 'website-development',
            title: 'Healthcare Practice Improves Patient Experience',
            description: 'Medical practice built patient portal and appointment booking system to streamline healthcare delivery.',
            client_name: 'CarePlus Medical',
            industry: 'Healthcare',
            results: { 'patient_satisfaction': '+150%', 'appointment_efficiency': '+200%', 'patient_portal_usage': '90%' },
            image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '51',
            service_type: 'website-development',
            title: 'Education Platform Serves 100K+ Students',
            description: 'Online learning platform built scalable infrastructure to handle massive student enrollment and course delivery.',
            client_name: 'EduScale',
            industry: 'Education',
            results: { 'student_capacity': '100K+', 'platform_uptime': '99.9%', 'course_completion': '+85%' },
            image_url: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '52',
            service_type: 'website-development',
            title: 'Real Estate Agency Automates Property Management',
            description: 'Property management company built comprehensive platform for listings, tenant management, and maintenance.',
            client_name: 'PropertyMaster',
            industry: 'Real Estate',
            results: { 'property_efficiency': '+250%', 'tenant_satisfaction': '+120%', 'maintenance_response': '+300%' },
            image_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '53',
            service_type: 'website-development',
            title: 'Restaurant Chain Launches Online Ordering Platform',
            description: 'Multi-location restaurant built integrated online ordering system with delivery tracking and loyalty programs.',
            client_name: 'TasteChain',
            industry: 'Food & Beverage',
            results: { 'online_orders': '+400%', 'delivery_efficiency': '+180%', 'customer_loyalty': '+150%' },
            image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '54',
            service_type: 'website-development',
            title: 'Non-Profit Organization Increases Donations by 300%',
            description: 'Charitable organization redesigned their website to optimize donation flows and volunteer engagement.',
            client_name: 'GiveHope',
            industry: 'Non-Profit',
            results: { 'donation_increase': '+300%', 'volunteer_signups': '+250%', 'community_engagement': '+200%' },
            image_url: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '55',
            service_type: 'website-development',
            title: 'Manufacturing Company Streamlines B2B Operations',
            description: 'Industrial manufacturer built customer portal for order tracking, specifications, and technical support.',
            client_name: 'IndustrialTech',
            industry: 'Manufacturing',
            results: { 'b2b_efficiency': '+200%', 'order_accuracy': '+95%', 'customer_support': '+180%' },
            image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 7,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '56',
            service_type: 'website-development',
            title: 'Financial Services Firm Builds Client Dashboard',
            description: 'Investment advisory firm created secure client portal for portfolio management and financial planning.',
            client_name: 'WealthDashboard',
            industry: 'Financial Services',
            results: { 'client_engagement': '+220%', 'portfolio_transparency': '+180%', 'service_efficiency': '+150%' },
            image_url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop',
            is_active: true,
            is_featured: false,
            sort_order: 8,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ]
      };

      // Enhanced stats with improved icons
      const statsData: { [key: string]: ServiceStat[] } = {
        'amazon-advertising': [
          {
            id: '1',
            service_type: 'amazon-advertising',
            stat_label: 'Average ROAS Increase',
            stat_value: '450%',
            stat_description: 'Return on advertising spend improvement',
            icon_name: 'TrendingUp',
            is_active: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '2',
            service_type: 'amazon-advertising',
            stat_label: 'Sales Growth',
            stat_value: '680%',
            stat_description: 'Average sales increase for our clients',
            icon_name: 'ShoppingCart',
            is_active: true,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '3',
            service_type: 'amazon-advertising',
            stat_label: 'ACoS Reduction',
            stat_value: '45%',
            stat_description: 'Average cost of sale optimization',
            icon_name: 'Target',
            is_active: true,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '4',
            service_type: 'amazon-advertising',
            stat_label: 'Keyword Rankings',
            stat_value: '95%',
            stat_description: 'Products ranking in top 10 positions',
            icon_name: 'Award',
            is_active: true,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'google-advertising': [
          {
            id: '5',
            service_type: 'google-advertising',
            stat_label: 'Click-Through Rate',
            stat_value: '8.5%',
            stat_description: 'Average CTR across all campaigns',
            icon_name: 'MousePointer',
            is_active: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '6',
            service_type: 'google-advertising',
            stat_label: 'Conversion Rate',
            stat_value: '12.3%',
            stat_description: 'Average conversion rate improvement',
            icon_name: 'Target',
            is_active: true,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '7',
            service_type: 'google-advertising',
            stat_label: 'Cost Reduction',
            stat_value: '35%',
            stat_description: 'Average cost per acquisition reduction',
            icon_name: 'DollarSign',
            is_active: true,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '8',
            service_type: 'google-advertising',
            stat_label: 'Quality Score',
            stat_value: '9.2/10',
            stat_description: 'Average Google Ads quality score',
            icon_name: 'Star',
            is_active: true,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'meta-advertising': [
          {
            id: '9',
            service_type: 'meta-advertising',
            stat_label: 'Engagement Rate',
            stat_value: '6.8%',
            stat_description: 'Average engagement across all campaigns',
            icon_name: 'Heart',
            is_active: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '10',
            service_type: 'meta-advertising',
            stat_label: 'Video View Rate',
            stat_value: '85%',
            stat_description: 'Average video completion rate',
            icon_name: 'Play',
            is_active: true,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '11',
            service_type: 'meta-advertising',
            stat_label: 'Reach Expansion',
            stat_value: '320%',
            stat_description: 'Average audience reach growth',
            icon_name: 'Users',
            is_active: true,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '12',
            service_type: 'meta-advertising',
            stat_label: 'Brand Awareness',
            stat_value: '+280%',
            stat_description: 'Brand recall improvement',
            icon_name: 'Eye',
            is_active: true,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'walmart-advertising': [
          {
            id: '13',
            service_type: 'walmart-advertising',
            stat_label: 'Sales Velocity',
            stat_value: '650%',
            stat_description: 'Average sales acceleration',
            icon_name: 'Zap',
            is_active: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '14',
            service_type: 'walmart-advertising',
            stat_label: 'Market Share',
            stat_value: '40%',
            stat_description: 'Average category market share captured',
            icon_name: 'PieChart',
            is_active: true,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '15',
            service_type: 'walmart-advertising',
            stat_label: 'Product Visibility',
            stat_value: '450%',
            stat_description: 'Increase in product impressions',
            icon_name: 'Eye',
            is_active: true,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '16',
            service_type: 'walmart-advertising',
            stat_label: 'Customer Rating',
            stat_value: '4.8/5',
            stat_description: 'Average product rating improvement',
            icon_name: 'Star',
            is_active: true,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'shopify-development': [
          {
            id: '17',
            service_type: 'shopify-development',
            stat_label: 'Conversion Rate',
            stat_value: '8.9%',
            stat_description: 'Average store conversion rate',
            icon_name: 'ShoppingBag',
            is_active: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '18',
            service_type: 'shopify-development',
            stat_label: 'Page Speed',
            stat_value: '2.1s',
            stat_description: 'Average page load time',
            icon_name: 'Gauge',
            is_active: true,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '19',
            service_type: 'shopify-development',
            stat_label: 'Mobile Revenue',
            stat_value: '65%',
            stat_description: 'Average mobile commerce share',
            icon_name: 'Smartphone',
            is_active: true,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '20',
            service_type: 'shopify-development',
            stat_label: 'Cart Recovery',
            stat_value: '35%',
            stat_description: 'Abandoned cart recovery rate',
            icon_name: 'RefreshCw',
            is_active: true,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'shopify-integration': [
          {
            id: '21',
            service_type: 'shopify-integration',
            stat_label: 'System Uptime',
            stat_value: '99.9%',
            stat_description: 'Integration reliability score',
            icon_name: 'Shield',
            is_active: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '22',
            service_type: 'shopify-integration',
            stat_label: 'Data Sync Speed',
            stat_value: '15s',
            stat_description: 'Average data synchronization time',
            icon_name: 'RotateCw',
            is_active: true,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '23',
            service_type: 'shopify-integration',
            stat_label: 'Process Automation',
            stat_value: '85%',
            stat_description: 'Tasks automated successfully',
            icon_name: 'Cpu',
            is_active: true,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '24',
            service_type: 'shopify-integration',
            stat_label: 'Error Reduction',
            stat_value: '90%',
            stat_description: 'Manual error elimination',
            icon_name: 'CheckCircle',
            is_active: true,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'website-development': [
          {
            id: '25',
            service_type: 'website-development',
            stat_label: 'Load Time',
            stat_value: '1.8s',
            stat_description: 'Average page load speed',
            icon_name: 'Clock',
            is_active: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '26',
            service_type: 'website-development',
            stat_label: 'SEO Score',
            stat_value: '95/100',
            stat_description: 'Average SEO optimization score',
            icon_name: 'Search',
            is_active: true,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '27',
            service_type: 'website-development',
            stat_label: 'Security Rating',
            stat_value: 'A+',
            stat_description: 'Website security grade',
            icon_name: 'Lock',
            is_active: true,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '28',
            service_type: 'website-development',
            stat_label: 'User Satisfaction',
            stat_value: '96%',
            stat_description: 'Client satisfaction rating',
            icon_name: 'Smile',
            is_active: true,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ]
      };

      // Reviews data
      const reviewsData: { [key: string]: ServiceReview[] } = {
        'amazon-advertising': [
          {
            id: '1',
            service_type: 'amazon-advertising',
            client_name: 'Sarah Johnson',
            company: 'KitchenPro',
            rating: 5,
            review_text: 'Our Amazon sales increased by 450% in just 6 months. The team\'s expertise in PPC optimization and keyword research is unmatched.',
            results_achieved: '450% sales increase, 35% ACoS reduction',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '2',
            service_type: 'amazon-advertising',
            client_name: 'Mike Chen',
            company: 'TechElite',
            rating: 5,
            review_text: 'Incredible results! We achieved 8x ROAS and dominated our competitive keywords. Professional service from start to finish.',
            results_achieved: '8.1x ROAS, 65% CTR increase',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '3',
            service_type: 'amazon-advertising',
            client_name: 'Emma Rodriguez',
            company: 'GlowBeauty',
            rating: 5,
            review_text: 'From startup to 7-figure revenue in 18 months. Their Amazon advertising strategy transformed our business completely.',
            results_achieved: '890% revenue growth, 320% brand search increase',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '4',
            service_type: 'amazon-advertising',
            client_name: 'David Park',
            company: 'FitGear Pro',
            rating: 5,
            review_text: 'We now rank #1 for our main keywords and saw 280% increase in organic traffic. Outstanding campaign management.',
            results_achieved: '#1 keyword rankings, 280% organic traffic boost',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '5',
            service_type: 'amazon-advertising',
            client_name: 'Lisa Thompson',
            company: 'HomeStyle',
            rating: 5,
            review_text: 'ACoS reduced by 60% while maintaining strong sales growth. Their bid management strategies are incredibly effective.',
            results_achieved: '60% ACoS reduction, 45% profit margin increase',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '6',
            service_type: 'amazon-advertising',
            client_name: 'James Wilson',
            company: 'PetLux',
            rating: 5,
            review_text: 'Built incredible brand loyalty with 85% increase and 2.5M+ video views. They understand Amazon\'s ecosystem perfectly.',
            results_achieved: '85% brand loyalty increase, 2.5M video views',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'google-advertising': [
          {
            id: '7',
            service_type: 'google-advertising',
            client_name: 'Rachel Green',
            company: 'CloudTech Solutions',
            rating: 5,
            review_text: 'Achieved 12x ROAS with Google Ads! Their keyword targeting and ad optimization strategies are phenomenal.',
            results_achieved: '12.3x ROAS, 70% cost per lead reduction',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '8',
            service_type: 'google-advertising',
            client_name: 'Tom Anderson',
            company: 'ShopSmart',
            rating: 5,
            review_text: 'Scaled from $500K to $2M annual revenue using Google Shopping and Performance Max. Incredible growth!',
            results_achieved: '$2M+ annual revenue, 350% shopping traffic increase',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '9',
            service_type: 'google-advertising',
            client_name: 'Maria Garcia',
            company: 'CoolAir Pro',
            rating: 5,
            review_text: 'Became the #1 HVAC company in our region. Local Services ads and search campaigns delivered amazing results.',
            results_achieved: '#1 local position, 220% service call increase',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '10',
            service_type: 'google-advertising',
            client_name: 'Dr. Steven Lee',
            company: 'Smile Dental',
            rating: 5,
            review_text: 'Patient volume increased by 300% and appointment bookings are up 150%. Excellent local targeting strategies.',
            results_achieved: '300% patient volume increase, 150% appointment rate',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '11',
            service_type: 'google-advertising',
            client_name: 'Jennifer Kim',
            company: 'LearnFast',
            rating: 5,
            review_text: 'User base grew by 500% with YouTube ads and search campaigns. Their education sector expertise is outstanding.',
            results_achieved: '500% user growth, 420% course enrollment increase',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '12',
            service_type: 'google-advertising',
            client_name: 'Robert Taylor',
            company: 'Prime Properties',
            rating: 5,
            review_text: 'Generating 150+ qualified leads monthly. Their real estate advertising strategies are incredibly effective.',
            results_achieved: '150+ monthly leads, 280% qualified prospect increase',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'meta-advertising': [
          {
            id: '13',
            service_type: 'meta-advertising',
            client_name: 'Sophie Martin',
            company: 'LuxeStyle',
            rating: 5,
            review_text: 'Achieved 15x ROAS on Meta! Their Instagram and Facebook ad strategies for luxury fashion are unmatched.',
            results_achieved: '15.2x ROAS, 450% brand engagement increase',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '14',
            service_type: 'meta-advertising',
            client_name: 'Alex Turner',
            company: 'FitLife App',
            rating: 5,
            review_text: 'Grew to 500K active users with Meta app install campaigns. User retention increased by 85%. Amazing results!',
            results_achieved: '500K+ active users, 800% app install increase',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '15',
            service_type: 'meta-advertising',
            client_name: 'Nina Patel',
            company: 'CozyHome',
            rating: 5,
            review_text: 'Built a community of 100K followers with 280% engagement rate. Their content strategy is brilliant.',
            results_achieved: '100K+ community, 280% engagement rate increase',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '16',
            service_type: 'meta-advertising',
            client_name: 'Chloe Davis',
            company: 'RadiantGlow',
            rating: 5,
            review_text: 'Our campaign went viral with 10M+ reach and 500+ influencer partnerships. Incredible brand awareness boost!',
            results_achieved: '10M+ viral reach, 650% brand mention increase',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '17',
            service_type: 'meta-advertising',
            client_name: 'Chef Marco',
            company: 'Gourmet Corner',
            rating: 5,
            review_text: 'Restaurant reservations increased by 300% with location-based targeting. Perfect for local businesses.',
            results_achieved: '300% reservation increase, 250% local awareness boost',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '18',
            service_type: 'meta-advertising',
            client_name: 'Dr. Amanda White',
            company: 'EduPro',
            rating: 5,
            review_text: 'Reached 1M students across 50+ countries. Their video ad strategies for education are exceptional.',
            results_achieved: '1M+ student base, 90% course completion rate',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'walmart-advertising': [
          {
            id: '19',
            service_type: 'walmart-advertising',
            client_name: 'Kevin Zhang',
            company: 'TechMax',
            rating: 5,
            review_text: 'Dominated Walmart with 680% sales growth and #1 category ranking. Their Walmart Connect expertise is incredible.',
            results_achieved: '680% sales growth, #1 category ranking',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '20',
            service_type: 'walmart-advertising',
            client_name: 'Linda Brown',
            company: 'HomeMaster',
            rating: 5,
            review_text: 'Achieved 900% revenue growth and became market leader. Their Walmart optimization strategies are outstanding.',
            results_achieved: '900% revenue growth, market leadership position',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '21',
            service_type: 'walmart-advertising',
            client_name: 'Grace Liu',
            company: 'PureGlow',
            rating: 5,
            review_text: 'Successfully launched on Walmart with top 10 ranking and 4.8/5 customer reviews. Excellent launch strategy.',
            results_achieved: 'Top 10 launch ranking, 4.8/5 customer rating',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '22',
            service_type: 'walmart-advertising',
            client_name: 'Ryan Mitchell',
            company: 'ActiveGear',
            rating: 5,
            review_text: 'Captured 40% category share with 250% inventory turnover improvement. Incredible sports category domination.',
            results_achieved: '40% category share, 250% inventory turnover',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '23',
            service_type: 'walmart-advertising',
            client_name: 'Carol Johnson',
            company: 'FarmFresh',
            rating: 5,
            review_text: 'Expanded from regional to nationwide distribution with 500% growth. Their expansion strategy was perfect.',
            results_achieved: 'Nationwide expansion, 500% distribution growth',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '24',
            service_type: 'walmart-advertising',
            client_name: 'Mark Stevens',
            company: 'AutoPro',
            rating: 5,
            review_text: 'B2B growth of 350% with 1000+ commercial clients. Walmart Business integration was seamless.',
            results_achieved: '350% B2B growth, 1000+ commercial clients',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'shopify-development': [
          {
            id: '25',
            service_type: 'shopify-development',
            client_name: 'Ashley Cooper',
            company: 'TrendSetters',
            rating: 5,
            review_text: 'Conversion rate increased by 180% with the new mobile-first design. Page speed improved by 90%. Excellent work!',
            results_achieved: '180% conversion rate increase, 90% page speed improvement',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '26',
            service_type: 'shopify-development',
            client_name: 'Daniel Kim',
            company: 'GadgetHub',
            rating: 5,
            review_text: 'Scaled to $10M revenue with Shopify Plus. Order processing improved by 300%. Outstanding development team.',
            results_achieved: '$10M+ annual revenue, 300% order processing improvement',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '27',
            service_type: 'shopify-development',
            client_name: 'Isabella Rodriguez',
            company: 'GlobalGlow',
            rating: 5,
            review_text: 'Expanded to 25+ countries with multi-language store. International sales increased by 400%. Amazing global solution.',
            results_achieved: '25+ global markets, 400% international sales increase',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '28',
            service_type: 'shopify-development',
            client_name: 'Oliver Chen',
            company: 'TasteCraft',
            rating: 5,
            review_text: 'Subscription revenue now 70% of total with 220% customer retention improvement. Perfect subscription setup.',
            results_achieved: '70% subscription revenue, 220% retention increase',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '29',
            service_type: 'shopify-development',
            client_name: 'Sophia Williams',
            company: 'ModernSpaces',
            rating: 5,
            review_text: 'Voice orders increased by 150% and AI recommendations boosted conversions by 85%. Cutting-edge technology.',
            results_achieved: '150% voice order increase, 85% AI recommendation boost',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '30',
            service_type: 'shopify-development',
            client_name: 'Marcus Johnson',
            company: 'AthleteConnect',
            rating: 5,
            review_text: 'Community engagement up 300% with 10K+ UGC posts. Brand loyalty increased by 180%. Incredible community features.',
            results_achieved: '300% community engagement, 10K+ UGC posts',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'shopify-integration': [
          {
            id: '31',
            service_type: 'shopify-integration',
            client_name: 'Victoria Lee',
            company: 'OmniStore',
            rating: 5,
            review_text: 'Unified all sales channels with 100% sync and 95% inventory accuracy. Operational efficiency up 180%.',
            results_achieved: '100% channel sync, 180% operational efficiency',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '32',
            service_type: 'shopify-integration',
            client_name: 'Nathan Park',
            company: 'BoxDelight',
            rating: 5,
            review_text: 'Automated 85% of processes with 200% CLV increase and 60% churn reduction. Perfect automation setup.',
            results_achieved: '85% automation rate, 200% CLV increase',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '33',
            service_type: 'shopify-integration',
            client_name: 'Elena Petrov',
            company: 'GlobalFashion',
            rating: 5,
            review_text: 'Connected global supply chain with 150% efficiency improvement. Now shipping to 40+ countries seamlessly.',
            results_achieved: '150% supply chain efficiency, 40+ countries reach',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '34',
            service_type: 'shopify-integration',
            client_name: 'Jason Wong',
            company: 'TechReturn',
            rating: 5,
            review_text: 'Returns processing improved by 300% with 120% customer satisfaction increase. Streamlined returns perfectly.',
            results_achieved: '300% return processing improvement, 120% satisfaction',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '35',
            service_type: 'shopify-integration',
            client_name: 'Dr. Sarah Mitchell',
            company: 'HealthTrack',
            rating: 5,
            review_text: '100% compliance rate with 250% audit efficiency improvement. Regulatory confidence increased by 180%.',
            results_achieved: '100% compliance rate, 250% audit efficiency',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '36',
            service_type: 'shopify-integration',
            client_name: 'Andrew Thompson',
            company: 'HomeFast',
            rating: 5,
            review_text: 'Delivery speed increased by 200% with 35% shipping cost reduction. Fulfillment accuracy up 95%.',
            results_achieved: '200% delivery speed increase, 35% cost reduction',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ],
        'website-development': [
          {
            id: '37',
            service_type: 'website-development',
            client_name: 'Patricia Adams',
            company: 'ConsultPro',
            rating: 5,
            review_text: 'Lead generation increased by 500% with 180% conversion rate improvement. Consultation bookings up 320%.',
            results_achieved: '500% lead generation increase, 320% consultation bookings',
            is_active: true,
            is_featured: true,
            sort_order: 1,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '38',
            service_type: 'website-development',
            client_name: 'Dr. Michael Foster',
            company: 'CarePlus Medical',
            rating: 5,
            review_text: 'Patient satisfaction up 150% with 200% appointment efficiency improvement. 90% patient portal usage.',
            results_achieved: '150% patient satisfaction, 200% appointment efficiency',
            is_active: true,
            is_featured: false,
            sort_order: 2,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '39',
            service_type: 'website-development',
            client_name: 'Professor Jane Smith',
            company: 'EduScale',
            rating: 5,
            review_text: 'Serving 100K+ students with 99.9% uptime. Course completion rate increased by 85%. Excellent scalability.',
            results_achieved: '100K+ student capacity, 99.9% platform uptime',
            is_active: true,
            is_featured: false,
            sort_order: 3,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '40',
            service_type: 'website-development',
            client_name: 'Richard Davis',
            company: 'PropertyMaster',
            rating: 5,
            review_text: 'Property efficiency up 250% with 120% tenant satisfaction. Maintenance response improved by 300%.',
            results_achieved: '250% property efficiency, 300% maintenance response',
            is_active: true,
            is_featured: false,
            sort_order: 4,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '41',
            service_type: 'website-development',
            client_name: 'Maria Gonzalez',
            company: 'TasteChain',
            rating: 5,
            review_text: 'Online orders increased by 400% with 180% delivery efficiency. Customer loyalty up 150%.',
            results_achieved: '400% online order increase, 180% delivery efficiency',
            is_active: true,
            is_featured: false,
            sort_order: 5,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          },
          {
            id: '42',
            service_type: 'website-development',
            client_name: 'John Harrison',
            company: 'GiveHope',
            rating: 5,
            review_text: 'Donations increased by 300% with 250% volunteer signups. Community engagement up 200%.',
            results_achieved: '300% donation increase, 250% volunteer signups',
            is_active: true,
            is_featured: false,
            sort_order: 6,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          }
        ]
      };

      setCaseStudies(caseStudiesData[serviceType] || []);
      setStats(statsData[serviceType] || []);
      setReviews(reviewsData[serviceType] || []);
    };

    generateServiceData();
  }, [serviceType]);

  return { caseStudies, stats, reviews };
};
