
-- Insert sample case studies for each service type
INSERT INTO service_case_studies (service_type, title, description, client_name, industry, results, image_url, is_featured, sort_order, is_active) VALUES
-- Amazon service case studies
('amazon', 'E-commerce Brand Increases Sales by 450%', 'A leading outdoor gear company transformed their Amazon presence through strategic PPC optimization and listing improvements.', 'OutdoorPro Inc', 'E-commerce', '{"sales_increase": "450%", "roas_improvement": "280%", "keyword_rankings": "Top 3 for 85% of target keywords"}', '/lovable-uploads/case-study-1.jpg', true, 1, true),
('amazon', 'Electronics Brand Dominates Competitive Category', 'Electronics startup achieved market leadership through comprehensive Amazon advertising strategy and brand optimization.', 'TechFlow Solutions', 'Electronics', '{"market_share": "35%", "sales_growth": "320%", "ad_spend_efficiency": "65% reduction in ACOS"}', '/lovable-uploads/case-study-2.jpg', true, 2, true),
('amazon', 'Home & Kitchen Brand Scales to 7-Figures', 'Family-owned kitchen brand achieved 7-figure revenue through strategic Amazon PPC and inventory management.', 'KitchenCraft Pro', 'Home & Kitchen', '{"revenue_growth": "680%", "units_sold": "50,000+ monthly", "profit_margin": "45% increase"}', '/lovable-uploads/case-study-3.jpg', false, 3, true),
('amazon', 'Health Supplement Brand Achieves 300% Growth', 'Nutritional supplement company tripled their Amazon revenue through targeted advertising and conversion optimization.', 'VitalHealth Co', 'Health & Wellness', '{"revenue_increase": "300%", "conversion_rate": "25% improvement", "customer_acquisition": "40% cost reduction"}', '/lovable-uploads/case-study-4.jpg', false, 4, true),
('amazon', 'Fashion Brand Conquers Seasonal Trends', 'Fashion retailer maximized seasonal opportunities with dynamic bidding strategies and trend-based campaigns.', 'StyleForward', 'Fashion', '{"seasonal_revenue": "520% increase", "brand_awareness": "300% lift", "customer_retention": "65% improvement"}', '/lovable-uploads/case-study-5.jpg', false, 5, true),
('amazon', 'Pet Products Brand Achieves Category Leadership', 'Pet supply company became category leader through strategic advertising and customer experience optimization.', 'PetPerfect Plus', 'Pet Products', '{"category_rank": "#1 in 12 subcategories", "sales_velocity": "400% increase", "review_score": "4.8/5 average"}', '/lovable-uploads/case-study-6.jpg', false, 6, true),
('amazon', 'Sports Equipment Brand Doubles Market Share', 'Athletic equipment manufacturer doubled market share through comprehensive Amazon growth strategy.', 'FitGear Pro', 'Sports & Outdoors', '{"market_share": "200% increase", "brand_recognition": "350% lift", "profit_margins": "30% improvement"}', '/lovable-uploads/case-study-7.jpg', false, 7, true),
('amazon', 'Beauty Brand Achieves International Expansion', 'Cosmetics company successfully expanded to 8 international Amazon marketplaces with localized strategies.', 'GlowBeauty', 'Beauty & Personal Care', '{"international_revenue": "280% of domestic", "marketplace_expansion": "8 countries", "brand_loyalty": "45% repeat purchase rate"}', '/lovable-uploads/case-study-8.jpg', false, 8, true),

-- Walmart service case studies
('walmart', 'Retail Brand Captures 40% Market Share on Walmart', 'Consumer goods company achieved dominant position on Walmart through strategic advertising and pricing optimization.', 'ConsumerChoice', 'Consumer Goods', '{"market_share": "40%", "revenue_growth": "380%", "profit_increase": "250%"}', '/lovable-uploads/walmart-case-1.jpg', true, 1, true),
('walmart', 'Electronics Retailer Boosts Walmart Sales 500%', 'Electronics distributor quintupled Walmart revenue through Walmart Connect advertising and inventory optimization.', 'ElectroMax', 'Electronics', '{"sales_increase": "500%", "ad_efficiency": "70% ROAS improvement", "inventory_turnover": "3x faster"}', '/lovable-uploads/walmart-case-2.jpg', true, 2, true),
('walmart', 'Home Goods Brand Dominates Walmart Marketplace', 'Home decor company became top seller in category through strategic Walmart Connect campaigns.', 'HomeStyle Elite', 'Home & Garden', '{"category_rank": "#1 seller", "revenue_growth": "420%", "customer_satisfaction": "4.9/5 rating"}', '/lovable-uploads/walmart-case-3.jpg', false, 3, true),
('walmart', 'Food Brand Achieves National Distribution', 'Specialty food manufacturer achieved nationwide Walmart presence through targeted advertising and logistics optimization.', 'TasteCraft Foods', 'Food & Beverage', '{"store_expansion": "2,000+ locations", "sales_volume": "300% increase", "brand_recognition": "85% lift"}', '/lovable-uploads/walmart-case-4.jpg', false, 4, true),
('walmart', 'Automotive Parts Supplier Scales Operations', 'Auto parts distributor scaled Walmart presence through strategic advertising and supply chain optimization.', 'AutoParts Direct', 'Automotive', '{"sales_growth": "350%", "operational_efficiency": "60% improvement", "customer_base": "10x expansion"}', '/lovable-uploads/walmart-case-5.jpg', false, 5, true),
('walmart', 'Health Products Brand Achieves Premium Positioning', 'Health and wellness company established premium brand positioning on Walmart through strategic marketing.', 'WellnessFirst', 'Health & Wellness', '{"premium_positioning": "Top 5% price tier", "sales_growth": "280%", "customer_loyalty": "70% repeat rate"}', '/lovable-uploads/walmart-case-6.jpg', false, 6, true),
('walmart', 'Toy Brand Dominates Holiday Sales', 'Toy manufacturer achieved record-breaking holiday sales through seasonal Walmart Connect strategies.', 'PlayTime Pro', 'Toys & Games', '{"holiday_sales": "600% increase", "inventory_velocity": "5x improvement", "market_penetration": "45% category share"}', '/lovable-uploads/walmart-case-7.jpg', false, 7, true),
('walmart', 'Apparel Brand Launches Successful Walmart Entry', 'Fashion brand successfully launched on Walmart marketplace with comprehensive advertising and positioning strategy.', 'FashionForward', 'Apparel', '{"launch_success": "Top 10 new brand", "sales_velocity": "250% above target", "customer_acquisition": "50% cost efficiency"}', '/lovable-uploads/walmart-case-8.jpg', false, 8, true),

-- Meta service case studies
('meta', 'E-commerce Brand Achieves 800% ROAS on Meta', 'Online retailer transformed their Meta advertising with advanced targeting and creative optimization strategies.', 'ShopSmart Online', 'E-commerce', '{"roas": "800%", "conversion_rate": "45% improvement", "customer_acquisition_cost": "60% reduction"}', '/lovable-uploads/meta-case-1.jpg', true, 1, true),
('meta', 'SaaS Company Scales with Meta Lead Generation', 'B2B software company achieved explosive growth through strategic Meta lead generation campaigns.', 'CloudTech Solutions', 'Technology', '{"lead_quality": "85% improvement", "cost_per_lead": "50% reduction", "sales_conversion": "40% increase"}', '/lovable-uploads/meta-case-2.jpg', true, 2, true),
('meta', 'Local Service Business Expands Market Reach', 'Home service company expanded from local to regional presence through targeted Meta advertising.', 'HomeServices Pro', 'Home Services', '{"market_expansion": "5 new cities", "lead_volume": "300% increase", "booking_rate": "65% improvement"}', '/lovable-uploads/meta-case-3.jpg', false, 3, true),
('meta', 'Fitness Brand Builds Community of 100K+ Followers', 'Fitness equipment company built massive engaged community through strategic Meta content and advertising.', 'FitLife Equipment', 'Fitness & Health', '{"community_growth": "100,000+ followers", "engagement_rate": "12% average", "sales_from_social": "40% of total revenue"}', '/lovable-uploads/meta-case-4.jpg', false, 4, true),
('meta', 'Restaurant Chain Drives 250% Increase in Orders', 'Regional restaurant chain dramatically increased online orders through targeted Meta advertising campaigns.', 'Gourmet Bites', 'Food & Restaurant', '{"online_orders": "250% increase", "customer_retention": "55% improvement", "average_order_value": "30% higher"}', '/lovable-uploads/meta-case-5.jpg', false, 5, true),
('meta', 'Education Platform Reaches 1M+ Students', 'Online education company scaled to over 1 million students through strategic Meta advertising and content marketing.', 'LearnForward Academy', 'Education', '{"student_acquisition": "1,000,000+ students", "course_completion": "75% rate", "customer_lifetime_value": "200% increase"}', '/lovable-uploads/meta-case-6.jpg', false, 6, true),
('meta', 'Beauty Brand Achieves Viral Success', 'Cosmetics startup achieved viral growth through creative Meta campaigns and influencer partnerships.', 'GlowUp Beauty', 'Beauty & Cosmetics', '{"viral_reach": "50M+ impressions", "sales_spike": "1,200% in 30 days", "brand_mentions": "500% increase"}', '/lovable-uploads/meta-case-7.jpg', false, 7, true),
('meta', 'Real Estate Agency Generates 500+ Quality Leads Monthly', 'Real estate company transformed lead generation through strategic Meta advertising and landing page optimization.', 'PrimeProperties', 'Real Estate', '{"monthly_leads": "500+ qualified leads", "conversion_rate": "35% improvement", "average_deal_size": "25% increase"}', '/lovable-uploads/meta-case-8.jpg', false, 8, true);

-- Insert sample stats for each service type
INSERT INTO service_stats (service_type, stat_label, stat_value, stat_description, icon_name, sort_order, is_active) VALUES
-- Amazon stats
('amazon', 'Average Sales Increase', '350%', 'Average sales growth for our Amazon clients within 90 days', 'TrendingUp', 1, true),
('amazon', 'ROAS Improvement', '280%', 'Average return on ad spend improvement across all campaigns', 'Target', 2, true),
('amazon', 'Keywords Ranked Top 3', '85%', 'Percentage of target keywords ranking in top 3 positions', 'Search', 3, true),
('amazon', 'Client Retention Rate', '96%', 'Percentage of clients who continue working with us year-over-year', 'Users', 4, true),

-- Walmart stats
('walmart', 'Average Revenue Growth', '380%', 'Average revenue increase for Walmart marketplace clients', 'ShoppingCart', 1, true),
('walmart', 'Market Share Captured', '40%', 'Average market share gained in client product categories', 'PieChart', 2, true),
('walmart', 'Inventory Turnover', '3x', 'Improvement in inventory velocity and turnover rates', 'RefreshCw', 3, true),
('walmart', 'Customer Satisfaction', '4.8/5', 'Average customer rating across all managed Walmart listings', 'Star', 4, true),

-- Meta stats
('meta', 'Average ROAS Achievement', '650%', 'Average return on ad spend across all Meta campaigns', 'Target', 1, true),
('meta', 'Cost Per Lead Reduction', '55%', 'Average reduction in cost per lead through optimization', 'TrendingDown', 2, true),
('meta', 'Conversion Rate Lift', '45%', 'Average improvement in conversion rates for clients', 'ArrowUp', 3, true),
('meta', 'Audience Reach Expansion', '300%', 'Average increase in qualified audience reach', 'Users', 4, true);

-- Insert sample reviews for each service type
INSERT INTO service_reviews (service_type, client_name, company, rating, review_text, avatar_url, results_achieved, sort_order, is_active) VALUES
-- Amazon reviews
('amazon', 'Sarah Johnson', 'Outdoor Gear Pro', 5, 'The team completely transformed our Amazon presence. Our sales increased by 450% in just 3 months, and we are now ranking #1 for most of our target keywords. Their expertise in PPC optimization is unmatched.', '/lovable-uploads/avatar-1.jpg', '450% sales increase, #1 rankings for 85% of keywords', 1, true),
('amazon', 'Mike Chen', 'TechFlow Electronics', 5, 'Working with this team was a game-changer for our electronics brand. They helped us achieve a 320% increase in sales while reducing our advertising costs. Their strategic approach to Amazon advertising is phenomenal.', '/lovable-uploads/avatar-2.jpg', '320% sales growth, 65% reduction in ACOS', 2, true),
('amazon', 'Emily Rodriguez', 'KitchenCraft Pro', 5, 'From a small family business to 7-figure revenue on Amazon - this team made it possible. Their attention to detail and continuous optimization resulted in a 680% revenue increase. Highly recommended!', '/lovable-uploads/avatar-3.jpg', '680% revenue growth, 50,000+ units sold monthly', 3, true),
('amazon', 'David Park', 'VitalHealth Supplements', 4, 'The results speak for themselves - 300% revenue increase and significantly improved conversion rates. The team is professional, responsive, and truly understands the Amazon ecosystem.', '/lovable-uploads/avatar-4.jpg', '300% revenue increase, 25% conversion rate improvement', 4, true),
('amazon', 'Lisa Thompson', 'StyleForward Fashion', 5, 'Their seasonal campaign strategies helped us achieve a 520% increase in revenue during peak seasons. The team understands fashion trends and timing perfectly. Excellent partnership!', '/lovable-uploads/avatar-5.jpg', '520% seasonal revenue increase, 300% brand awareness lift', 5, true),
('amazon', 'Robert Kim', 'PetPerfect Plus', 5, 'We became the #1 seller in 12 pet product subcategories thanks to their expertise. The 400% increase in sales velocity and improved customer reviews transformed our business completely.', '/lovable-uploads/avatar-6.jpg', '#1 in 12 subcategories, 400% sales velocity increase', 6, true),

-- Walmart reviews
('walmart', 'Jennifer Martinez', 'ConsumerChoice Brands', 5, 'Achieving 40% market share on Walmart seemed impossible until we partnered with this team. Their Walmart Connect expertise and strategic approach delivered a 380% revenue increase. Outstanding results!', '/lovable-uploads/avatar-7.jpg', '40% market share, 380% revenue growth', 1, true),
('walmart', 'Tom Wilson', 'ElectroMax Distribution', 5, 'Our Walmart sales increased by 500% within 6 months. The team understands Walmart marketplace dynamics better than anyone. Their optimization strategies are incredibly effective.', '/lovable-uploads/avatar-8.jpg', '500% sales increase, 70% ROAS improvement', 2, true),
('walmart', 'Amanda Foster', 'HomeStyle Elite', 4, 'Becoming the #1 seller in our category on Walmart was a dream come true. The team delivered a 420% revenue growth and helped us maintain a 4.9/5 customer rating. Fantastic work!', '/lovable-uploads/avatar-9.jpg', '#1 category seller, 420% revenue growth', 3, true),
('walmart', 'Carlos Mendoza', 'TasteCraft Foods', 5, 'Expanding to 2,000+ Walmart locations with a 300% sales increase - this team made the impossible possible. Their understanding of food retail and Walmart ecosystem is exceptional.', '/lovable-uploads/avatar-10.jpg', '2,000+ store locations, 300% sales increase', 4, true),
('walmart', 'Rachel Green', 'AutoParts Direct', 5, 'The 350% sales growth and 60% operational efficiency improvement transformed our business. Working with this team was the best decision we made for our Walmart marketplace strategy.', '/lovable-uploads/avatar-11.jpg', '350% sales growth, 60% efficiency improvement', 5, true),
('walmart', 'James Liu', 'WellnessFirst Products', 4, 'Achieving premium positioning in the top 5% price tier while growing sales by 280% - this team knows how to balance brand value with growth. Highly professional service.', '/lovable-uploads/avatar-12.jpg', 'Top 5% premium positioning, 280% sales growth', 6, true),

-- Meta reviews
('meta', 'Nicole Adams', 'ShopSmart Online', 5, 'Achieving 800% ROAS on Meta seemed impossible until we started working with this team. Their advanced targeting and creative optimization strategies transformed our entire business. Incredible results!', '/lovable-uploads/avatar-13.jpg', '800% ROAS, 45% conversion rate improvement', 1, true),
('meta', 'Alex Turner', 'CloudTech Solutions', 5, 'Our B2B lead generation was completely transformed. 85% improvement in lead quality and 50% reduction in cost per lead - this team understands Meta advertising for B2B like no one else.', '/lovable-uploads/avatar-14.jpg', '85% lead quality improvement, 50% cost reduction', 2, true),
('meta', 'Maria Gonzalez', 'HomeServices Pro', 4, 'Expanding from local to 5 new cities with a 300% increase in leads - this team helped us scale beyond our wildest dreams. Their local marketing expertise on Meta is outstanding.', '/lovable-uploads/avatar-15.jpg', '5 city expansion, 300% lead increase', 3, true),
('meta', 'Kevin Zhang', 'FitLife Equipment', 5, 'Building a community of 100,000+ engaged followers and generating 40% of our revenue from social - this team created a complete transformation. Their community-building strategies are phenomenal.', '/lovable-uploads/avatar-16.jpg', '100,000+ followers, 40% revenue from social', 4, true),
('meta', 'Sophia Brown', 'Gourmet Bites', 5, 'Our online orders increased by 250% and customer retention improved by 55%. The team understands restaurant marketing on Meta perfectly. The ROI has been exceptional.', '/lovable-uploads/avatar-17.jpg', '250% order increase, 55% retention improvement', 5, true),
('meta', 'Daniel Cooper', 'LearnForward Academy', 5, 'Scaling to over 1 million students through Meta advertising was beyond our expectations. The team delivered a 200% increase in customer lifetime value. Truly impressive results!', '/lovable-uploads/avatar-18.jpg', '1M+ students acquired, 200% CLV increase', 6, true);
